# Generated by Django 5.1.3 on 2024-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo de Producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del Producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Inventario')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Producto')),
            ],
        ),
    ]
