# Generated by Django 5.0.6 on 2024-12-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_produtoscompras_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoscompras',
            name='id_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produtoscompras',
            name='id_product',
            field=models.IntegerField(),
        ),
    ]
