# Generated by Django 5.0.6 on 2024-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_produtoscompras_id_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='transbank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=100)),
                ('token', models.CharField(default='0', max_length=100)),
                ('id_compras', models.IntegerField(default=0)),
                ('response_code', models.CharField(default='-1', max_length=2)),
                ('authorization_code', models.CharField(default='0', max_length=10)),
                ('payment_type_code', models.CharField(default='0', max_length=2)),
                ('installments_number', models.IntegerField(default=0)),
                ('installments_amount', models.IntegerField(default=0)),
                ('card_number', models.CharField(default='0', max_length=10)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
